---
apiVersion: v1
kind: Namespace
metadata:
  name: opentelemetry-operator-system

---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adot-collector-role
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - extensions
    resources:
      - ingresses
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs:
      - /metrics
    verbs:
      - get

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: adot-collector-role-binding
subjects:
- kind: ServiceAccount
  name: adot-collector-sa
  namespace: opentelemetry-operator-system
roleRef:
  kind: ClusterRole
  name: adot-collector-role
  apiGroup: rbac.authorization.k8s.io

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector-sa
  namespace: opentelemetry-operator-system
